ALI:
  PAY:
#支付宝网关（固定）
    URL: https://openapi.alipaydev.com/gateway.do
#阿里官方支付公钥
    PUBLIC_KEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB
#APPID 即创建应用后生成
    APP_ID: 2016101300678419
#参数返回格式，只支持 json 格式
    FORMAT: json
    CHARSET: UTF-8
#商户生成签名字符串所使用的签名算法类型
    SIGN_TYPE: RSA2
#   app公钥证书路径
    appCertPublicKeyPath: D:\CSR\appCertPublicKey.crt
#   支付宝公钥证书书路径
    alipayCertPublicKey_RSA2Path: D:\CSR\alipayCertPublicKey_RSA2.crt
#   支付宝根证书路径
    alipayRootCertPath: D:\\CSR\\alipayRootCert.crt
#我的应用公私钥
    APP:
      PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHcklj3P5drDKd1ElsXzX3/6kEfnhbSp5N/+Nqkrvw5gg4N7C8bvCtmox08p6c2DWMeAiv5B23zE8gy4xfkphtNEgQrVXAkJSge9BEuFsXmr7IoGALp4y14Y7hJlms6IBelgo3p/fWfvT3NTkA2Xt5Ccfc1DQm7piwajvMHMJ4EIddXOu/+5tL7gX7FhplK8AFcz/K0bEZU3vWW24cQBReC5xUExft22CeamYNNhoNmZ0SOMecZI3aa2e7Ktwbg1V1WkJbr+lZm3vn+taHb0eJXdhq5VK/PyZj4UasHVRZiimaT4hre6npgcd7Kn5JI1rlTOLcJaGt7cynEZG3cbstAgMBAAECggEAXq0L1ZHkVYcWiAFr0TvpHI6KJw36CCwFtbUQuVhqStKHeFhHV0u6iE5i+mjpjj68PLAGP6ijysn7je/R9NRb8wrsYq5FlKGNTBk6JkT1SOE2S3qF3UJt8zDdaFeSHhhIR54lv4HGjlW551emdZbHnA9ehp9dGlYMuUHUnPHSBrfKRq/NggAiLvAufHQV663zFtY62EydKU0zBQS1Qb/bjw1jYIcvyc+Elf0/1G7s/8TTpUpOihdDQAnoNLlilxp7pgi4R0KRqmgYI/Qr58EpeVypRHntg1D0nlmOU65Sf6NDBaS0+8q0jF3PUTklBQEpLlGKBzJ+3Hvaq752ws4jqQKBgQD6KIsa3VXcPu72J3MOBK6rnAOmBx/bXzGbWpw0YB71o1dhlMEAWG21icjBvkUXu/CyVXdYundrTgVwud+J883XzyI7iOnfKrhEXpkYXCAr313yj/GL44b4AR1H7M9doP6xoMu5ccSKDK1HxsrrAV15nG003nEvJ0g+i0UyljpQ4wKBgQDMGpXXpq2tamyCrhNeiSxU76eCmqMX2t0hW6PjEJCYDFfQ17CfauhGbd3Yf5nJqm8r7OlLj5s68c0i6Lnn8wkOlpjxk5oS1Pbpjzz6OVrqI3CpO2rqFYPhCkmTsi6xTXCarTPePn6nupQeahiGeZsBkAO8Vguwdv1Qj1rsn3TQrwKBgQCsmYCw/noZRorV6A4oY+6olTKnQU8nqxytFe2k7ZUu4o6N03b+6AR6NyD/HGrLn27JfNKls7JlpSV3y6eCpWcnOdFixmqnAfC1q5dyCU5hNvK5Q7vjSw962jn7wFarQUO6BznJL8ftgCWm2nBziTOXjuiCi+AIKtBb5vfNmX2PBQKBgG7muyiUPqaNvyw6nfeuHVKBbcl/cMMTfzgS7TgB1i9n9Yday3OzyUYLiJGMs+lqHEIH1rPh8fzTSh1/yxQHcJJmrfAFvaAh64/47q8f3xB99UdfK7bJvgDXcCc6mDhq1ZaWKirGVleY/8aO64iWJu1wbTc2od9eqEHPwx3zfqutAoGBAM5dyLZ/iMiboQcTE7QMgxIKIBmhn5FXNvSeluEOPk4NA3pp8PfgVYwkLjZHyvTDsEJL+VElL3P/PTH2UpAIaChk3Jh8sSk3rCCD7nrPj0rhX04LHgei3Dabm/dpHGcm00hb0mmD64aI3Ctq6lwU2C6fHk6lLW09Clnwf0gRw4kY
      PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3JJY9z+XawyndRJbF819/+pBH54W0qeTf/japK78OYIODewvG7wrZqMdPKenNg1jHgIr+Qdt8xPIMuMX5KYbTRIEK1VwJCUoHvQRLhbF5q+yKBgC6eMteGO4SZZrOiAXpYKN6f31n709zU5ANl7eQnH3NQ0Ju6YsGo7zBzCeBCHXVzrv/ubS+4F+xYaZSvABXM/ytGxGVN71ltuHEAUXgucVBMX7dtgnmpmDTYaDZmdEjjHnGSN2mtnuyrcG4NVdVpCW6/pWZt75/rWh29HiV3YauVSvz8mY+FGrB1UWYopmk+Ia3up6YHHeyp+SSNa5Uzi3CWhre3MpxGRt3G7LQIDAQAB