server:
  port: 8084
  servlet:
    context-path: /dream

#mysql druid连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dream_mysql?serverTimezone=UTC
      username: root
      password: 123456
      #连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒）
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      #包含common文件
  profiles:
    include: common

#mybatis
mybatis:
  type-aliases-package: com.shibro.nativeproducts.data.entity
  mapper-locations: classpath:config/mybatis/*.xml
